server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: accountRoute # Route identifier for account-service
          uri: lb://account-service # URI to redirect given the predicate
          predicates: # Request analysis rules
            - Path=/accounts/** # URL path of request url to consider
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**

      default-filters:
        - name: LogFilter # Default Filter for all requests

      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway